version: '3'
services:

  patientdb:
    image: mysql:8.0
    networks:
      - web-server    
    container_name: patientdb
    volumes:
      - "./init-scripts:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=patient_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10  


  notesdb:
    image: mongo
    container_name: notedb
    volumes:
      - ./notes-database:/notes-database
    command:
      - /notes-database/import.sh
    environment:
      MONGO_INITDB_DATABASE: mediscreen
    ports:
      - 27017:27017

  patient_ms:
    image: patient_ms
    networks:
      - web-server    
    depends_on:
      - patientdb
#        condition: service_healthy
    container_name: patient_ms
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://patientdb:3306/patient_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASROUCE_PASSWORD=root

    ports:
      - "8080:8080"


  notes_ms:
    image: notes_ms
    networks:
      - web-server
    depends_on:
      - notes-database
    container_name: notes_ms
    ports:
      - "8181:8181"
#    restart: always
#
#  assessment_ms:
#    image: assessment_ms
#    networks:
#      - web-server
#    container_name: assessment_ms
#    ports:
#      - "8282:8282"
#    restart: always

#  mediscreen-angular:
#    container_name: mediscreen-angular
#    build: mediscreen-angular
#    ports:
#      - 4200:4200

#
#volumes:
#  dbdata:
###########################
#        NETWORK
###########################
networks:
  web-server:
    driver: bridge
