FROM mongo:latest

#COPY . /data/db
#
#RUN mongod --fork --logpath /var/log/mongodb.log --dbpath /data/db
#    && CREATE_FILES=/data/db/scripts/*-create.js
#    && for f in $CREATE_FILES; do mongo 127.0.0.1:27017 $f; done
#    && INSERT_FILES=/data/db/scripts/*-insert.js
#    && for f in $INSERT_FILES; do mongo 127.0.0.1:27017 $f; done
#    && mongod --shutdown