FROM mongo:latest

#COPY ./init-db.d/notesdb.json /docker-entrypoint-initdb.d
#! /bin/bash
#CMD mongoimport --host mongodb --db mediscreen --collection notes --type json --file /notesdb.json --jsonArray
CMD echo dockerfile